name = "SphereQuadratures"
uuid = "45860e12-b938-4b73-b56f-7621cdbdeff9"
authors = ["victorjesusamoresmedianero <victorjesus.amores@upm.es> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.7"
DataFrames = "0.21"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
