name = "SphereQuadratures"
uuid = "45860e12-b938-4b73-b56f-7621cdbdeff9"
authors = ["victorjesusamoresmedianero <victorjesus.amores@upm.es> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
